language: "en"
early_access: false
reviews:
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  path_filters:
    - "!**/.xml"
  path_instructions:
    - path: "**/*.cs"
      instructions: |
        Review C# source ensuring:
        - No usage of MediatR or prohibited frameworks.
        - Application services pattern (method-per-use-case) maintained.
        - Nullable warnings addressed; prefer guard clauses.
        - LINQ remains readable; avoid excessive chaining complexity.
        - Domain invariants enforced in entity Create methods/static factories.
    - path: "tests/**/*"
      instructions: |
        Assess xUnit tests:
        - Follow Arrange/Act/Assert pattern.
        - Deterministic (no reliance on real clock without abstraction).
        - Meaningful assertions (not solely non-null checks).
        - Coverage of edge cases (overlapping assignments, leap-year rollover, leave spanning weekends).
    - path: "**/*.razor"
      instructions: |
        Blazor components:
        - Keep business logic minimal; delegate to services.
        - Use MudBlazor components consistently; no inline JS unless essential.
        - Parameter naming clear; avoid ambiguous abbreviations.
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
    base_branches:
      - "main"
chat:
  auto_reply: false
